### ISSUE TITLE
Does emacs vterm compile on mac?

### ISSUE THREAD

**Issue by PlumpMath** [shaunsingh/nix-darwin-dotfiles#15]
First of all, thank you for sharing your settings.

It's no different than setting up vterm, so I studied flake for a day and a half yesterday, and I learned it properly from you.
But I am new to emacs vterm; I wanted to do it. But it doesn't compile on my Mac.

pam fingerprint unlock setting is really great. I love it~*

**Comment by shaunsingh** [comment]
I  haven't updated my config in a while. Its probably an issue with outdated flake inputs, I'll take a look soon

**Comment by PlumpMath** [comment]
Just install it with brew and it works.

**Comment by shaunsingh** [comment]
Looks like its building (for now), let me know if anything breaks
