### ISSUE TITLE
Consider packaging sway with rounded borders to nixpkgs

### ISSUE THREAD

**Issue by Ashe** [shaunsingh/nix-darwin-dotfiles#5]
Hey! Your setup is looking very nice and you should be proud of what you've done!

I was thinking of using the rounded-borders you have got going with sway, but I feel like there's going to be plenty of other people who will want rounded borders too! 

Have you considered making a package specifically for your borders so that people can override the default package via home manager? Would be nice to just grab it from nixpkgs :)

**Comment by shaunsingh** [comment]
It doesn't make much sense packaging sway-borders for nixpkgs (as all I'm doing is overwriting the source repo for sway and adding a dependency), but I did make my overlay into an external repo so you can use that now: 

To install it you can take a look at how i do it with my nix flake (see https://github.com/shaunsingh/nix-darwin-dotfiles/blob/69c27ee4f43bb5e26205da72fb32a29b864c0479/flake.nix#L69-L89 and all references of `nixpkgs-overlays` in that file

After that you can install the package like normal (e.g. just add `sway-borders-git` to your list of packages)

LMK if you need anything else :)

**Comment by shaunsingh** [comment]
https://github.com/shaunsingh/nixpkgs-s2k for instructions/questions/documentation

**Comment by Ashe** [comment]
Thank you and that's fine! I'll give it a try tonight :)
