### ISSUE TITLE
installation on a mac os monterey 

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [shaunsingh/nix-darwin-dotfiles#8]
hello, I wanted to try your config, I corrected it for myself, but at the moment of installation I got this 
[nix-shell:~/nix-darwin-dotfiles]$ ./result/sw/bin/darwin-rebuild switch --flake .#shaunsingh-laptop
warning: Git tree '/Users/vh/nix-darwin-dotfiles' is dirty
building the system configuration...
warning: Git tree '/Users/vh/nix-darwin-dotfiles' is dirty
Password:
error: Directory /run does not exist, aborting activation
Create a symlink to /var/run with:

$ sudo ln -s private/var/run /run
maybe I should remount the system partition

**Comment by shaunsingh** [comment]
yup had the same issue, was fixed recently upstream in `nix-darwin`, I assume the issue doesn't occur anymore?

**Comment by shaunsingh** [comment]
I was initially working on a launchd daemon that would make everything light or dark theme depending on your system settings, but it doesn't work anymore because apple changed some stuff on their end. I'll revisit the idea sometime.

**Comment by xxxvik-xakerxxx** [comment]
> I was initially working on a launchd daemon that would make everything light or dark theme depending on your system settings, but it doesn't work anymore because apple changed some stuff on their end. I'll revisit the idea sometime.

then at least a preset from the author where in the script you can specify the theme that the user wants

**Comment by shaunsingh** [comment]
I think a better idea would be to use https://github.com/SenchoPens/base16.nix to have nix load a base16 theme and use that for spacebar/alacritty/firefox/Tmux

**Comment by xxxvik-xakerxxx** [comment]
> https://github.com/SenchoPens/base16.nix

I think it's a great idea

**Comment by xxxvik-xakerxxx** [comment]
> I think a better idea would be to use https://github.com/SenchoPens/base16.nix to have nix load a base16 theme and use that for spacebar/alacritty/firefox/Tmux

why not use let's say pywal it is in nix and should work great if configured correctly?
